# Change these first
owner: martin-sun # Your GitHub organization or username, where this repository lives
repo: woohelps-upptime # The name of this repository

sites:
  - name: Woohelps-com
    url: https://www.woohelps.com
    method: HEAD
    expectedStatusCodes:
      - 200
      - 301
      - 302
    maxResponseTime: 10000   # 毫秒，超过将记为慢   
  - name: Woohelps-cn
    url: https://www.woohelps.cn
    method: HEAD
    expectedStatusCodes:
      - 200
      - 301
      - 302
    maxResponseTime: 10000   # 毫秒，超过将记为慢   
  - name: Catalysis Division
    url: https://www.catalysisdivision.ca/
    method: HEAD
    expectedStatusCodes:
      - 200
      - 301
      - 302
    maxResponseTime: 10000   # 毫秒，超过将记为慢 
  - name: Woohelps-merchant
    url: https://merchant.woohelps.com
    
  - name: Ticktheorder
    url: https://www.ticktheorder.com
  - name: Summer Palace
    url: https://www.summerpalace.ca
  - name: Woohelps-Cloud
    url: https://cloud.woohelps.com
    method: HEAD
    expectedStatusCodes:
      - 200
      - 301
      - 302
    maxResponseTime: 10000   # 毫秒，超过将记为慢   
  - name: Woohelps-SMS
    url: https://sms.woohelps.com
    method: HEAD
    expectedStatusCodes:
      - 200
      - 301
      - 302
    maxResponseTime: 10000   # 毫秒，超过将记为慢   
  - name: Woohelps-API
    url: https://api.woohelps.com
    method: HEAD
    expectedStatusCodes:
      - 200
      - 301
      - 302
    maxResponseTime: 10000   # 毫秒，超过将记为慢   
  - name: Woohelps-service
    url: https://service.woohelps.com
    method: HEAD
    expectedStatusCodes:
      - 200
      - 301
      - 302
    maxResponseTime: 10000   # 毫秒，超过将记为慢 
  - name: Beanflow-api
    url: https://api.beanflow.ai
  - name: Beanflow
    url: https://www.beanflow.ai
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /woohelps-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
